"""The guide: its generated reference chapters and its build (0042-agora FR-034, FR-035).

`reference_files` writes the chapters that are taken from the code, each from the registry, the help topics, the toolchain entries,
the check sections and the design systems, so that `fresh` can prove them current. `build` turns `docs-src/` into four editions
with the toolchain's converters, and `link_findings` proves the multi-page site's links resolve. Standard library only.
"""
from __future__ import annotations

import html
import re
import shutil
import tempfile
from html.parser import HTMLParser
from pathlib import Path
from typing import Any, Callable

from agora.core import system
from agora.core.describe import command_data
from agora.core.registry import CATEGORIES, Registry
from agora.core.types import ArgType, Choice, Dynamic, Pattern
from . import design_systems, specs
from .skill import CATEGORY_HELP

SRC = "docs-src"
GENERATOR = "reference-docs"
REWRITE = "docs generate"
BRAND = "design-systems/frontiers-brand"
# What the site and the landing page use from the brand, copied beside the page by `docs build` (0042 FR-035): output name -> source.
ASSETS = {
    "logo.png": f"{BRAND}/logos/if-logo-672x189-2026-Sept.png",
    "logo-dark.png": f"{BRAND}/logos/if-logo-dark-672x189-2026-Sept.png",
    "logo-wide.png": f"{BRAND}/logos/if-logo-1229x362-2026-Sept.png",
    "icon.png": f"{BRAND}/logos/if-icon-423x358-2026-Sept.png",
    "logo.webp": f"{BRAND}/logos/web/if-logo-672x189-2026-Sept.webp",
    "logo-dark.webp": f"{BRAND}/logos/web/if-logo-dark-672x189-2026-Sept.webp",
    "favicon.png": f"{BRAND}/images/favicon.png",
    "share-card.png": f"{BRAND}/images/share-card.png",
    "hero.webp": f"{BRAND}/imagery/web/mountain-railway-trestle-station-1448.webp",
    "hero-small.webp": f"{BRAND}/imagery/web/mountain-railway-trestle-station-724.webp",
    "brand.css": f"{BRAND}/brand.css",
    "InterVariable.ttf": f"{BRAND}/fonts/InterVariable.ttf",
}
EDITIONS = ("multi-page HTML", "single-page HTML", "PDF", "EPUB")


def header(name: str = GENERATOR, rewrite: str = REWRITE) -> str:
    return (f"// Generated by the {name} generator from agora's code. Do not edit it by hand: run `agora {rewrite}` to rewrite it, "
            "`agora fresh` to prove it current.\n")


def _cell(s: Any) -> str:
    return str(s).replace("|", "\\|").replace("\n", " ")


def _block(text: str) -> list[str]:
    """A help topic's text as AsciiDoc: paragraphs as they are, and lines indented four spaces as listing blocks."""
    out: list[str] = []
    code: list[str] = []
    for line in text.split("\n"):
        if line.startswith("    "):
            code.append(line[4:])
            continue
        if code:
            out += ["----", *code, "----", ""]
            code = []
        out.append(line)
    if code:
        out += ["----", *code, "----"]
    return out


# ---- the reference chapters --------------------------------------------------------------------------------------

def commands_chapter(reg: Registry) -> str:
    name = reg.name
    lines = [header(), "[#reference-commands]", "== Command reference", "",
             f"Every command, taken from the registry. `{name} command list` and `{name} command show COMMAND` say the same, and "
             f"`{name} help` is where the daily work is explained, step by step. A command is `{name} NOUN VERB [ID] [options]`; "
             "every command takes `--json`, and one that writes takes `--dry-run`.", "",
             "[cols=\"1,4\"]", "|===", "|Category |What it may do", ""]
    for c in CATEGORIES:
        lines += [f"|`{c}`", f"|{_cell(CATEGORY_HELP[c])}", ""]
    lines += ["|===", ""]
    by_noun: dict[str, list] = {}
    for c in sorted(reg.commands.values(), key=lambda c: c.id):
        by_noun.setdefault(c.noun or "", []).append(c)
    order = [""] + sorted(n for n in by_noun if n)
    for noun in order:
        cmds = by_noun.get(noun)
        if not cmds:
            continue
        if noun:
            lines += [f"=== {noun}", "", _cell(reg.nouns.get(noun, "")), ""]
        else:
            lines += ["=== Repository-wide commands", "", "These take no noun.", ""]
        lines += ['[cols="4,2,2,4"]', "|===", "|Usage |Category |Where it runs |What it does", ""]
        for c in cmds:
            d = command_data(reg, c)
            lines += [f"|`{_cell(d['usage'])}`", f"|{c.category}", f"|{_cell(', '.join(d['surfaces']))}", f"|{_cell(c.help)}", ""]
        lines += ["|===", ""]
    lines += ["=== Typed arguments", "",
              "A value that fails its type is an error that names the type and gives examples.", "",
              '[cols="1,3,3"]', "|===", "|Type |Is |Examples", ""]
    for t in sorted(reg.types.values(), key=lambda t: t.name):
        n, doc, eg = _type_row(t)
        lines += [f"|`{n}`", f"|{_cell(doc)}", f"|{_cell(eg)}", ""]
    lines += ["|===", ""]
    return "\n".join(lines)


def _type_row(t: ArgType) -> tuple[str, str, str]:
    if isinstance(t, Choice):
        eg = ", ".join(t.choices(None))
    elif isinstance(t, Pattern):
        eg = ", ".join(t.examples(None))
    else:
        eg = "a value `LIST` offers"
    return t.name, t.doc, eg.replace("LIST", "the noun's list command")


def checks_chapter(reg: Registry) -> str:
    name = reg.name
    suites = {s: v["sections"] for s, v in sorted(reg.suites.items())}
    lines = [header(), "[#reference-checks]", "== Checks, suites and generators", "",
             f"Every check runs through `{name} check [SECTION...]`. With nothing named it runs every section; `--suite` runs a named set, "
             f"`--scope` limits a section to one resource, and `--changed` runs only the sections whose watched files changed. A section "
             f"that cannot run says why and is skipped, never passed, and the run exits 3. `{name} help check` says which to run before "
             "you push.", "", "=== Sections", "", '[cols="1,5,1,2"]', "|===", "|Section |What it checks |Scope |Suites", ""]
    for s in sorted(reg.sections.values(), key=lambda s: s.name):
        in_suites = ", ".join(f"`{k}`" for k, v in suites.items() if any(n.split(" ")[0] == s.name for n in v)) or "none"
        lines += [f"|`{s.name}`", f"|{_cell(s.help)}", f"|{s.scope or 'none'}", f"|{in_suites}", ""]
    lines += ["|===", "", "=== Suites", "", '[cols="1,4"]', "|===", "|Suite |Sections", ""]
    for k, v in suites.items():
        opts = reg.suites[k].get("options", {})
        tail = "".join(f" (with --{o} {val})" for o, val in opts.items())
        lines += [f"|`{k}`", f"|{', '.join(f'`{n}`' for n in v)}{tail}", ""]
    lines += ["|===", "", "=== Generators", "",
              f"A generator writes tracked files from their sources. `{name} fresh` proves each current and writes nothing; when one is "
              "stale it names the command that rewrites it.", "", '[cols="1,3,2,2"]', "|===", "|Generator |What it writes |Rewritten by |Files", ""]
    for g in sorted(reg.generators.values(), key=lambda g: g.name):
        outs = ", ".join(f"`{o}`" for o in g.outputs)
        lines += [f"|`{g.name}`", f"|{_cell(g.help)}", f"|`{name} {g.command}`" if g.command else "|", f"|{outs}", ""]
    lines += ["|===", ""]
    return "\n".join(lines)


def help_chapter(reg: Registry) -> str:
    name = reg.name
    lines = [header(), "[#reference-help]", "== Help topics", "",
             f"The daily work is explained by `{name} help`. This chapter is the same text, taken from the same code, so that it cannot "
             "drift. In VS Code, the Learn command shows these pages with a button for each step.", ""]
    from agora.core.resource import Call
    for t in sorted(reg.topics.values(), key=lambda t: t.name):
        body = t.body()
        lines += [f"[#help-{t.name}]", f"=== {t.name}", "", f"_{t.summary}_", "", body["plain"], ""]
        for heading, text in body["sections"]:
            lines += [f"==== {heading}", "", *_block(text), ""]
        if body["steps"]:
            lines += ["==== Steps", ""]
            for s in body["steps"]:
                line = Call(s.command, dict(s.fields)).cli(reg, name)
                lines.append(f"* {s.label}: `{line}`" + (f" ({s.note})" if s.note else ""))
            lines.append("")
    return "\n".join(lines)


def toolchain_chapter(reg: Registry, entries: dict[str, Any]) -> str:
    name = reg.name
    lines = [header(), "[#reference-toolchain]", "== The toolchain", "",
             f"What `{name}` fetches for itself, because it has no Python wheel. Each entry is one exact version with an address and a "
             "SHA-256 for every platform it is built for, fetched into a per-user cache, checked before anything is unpacked, and "
             f"tested after. `{name} toolchain list` shows what your cache holds, and `{name} help toolchain` explains the work.", "",
             '[cols="1,1,4,2,1"]', "|===", "|Entry |Version |What it is |Platforms |Needs", ""]
    for e in sorted(entries.values(), key=lambda e: e.name):
        lines += [f"|`{e.name}`", f"|{_cell(e.version)}", f"|{_cell(e.summary)}", f"|{_cell(', '.join(sorted(e.platforms)))}",
                  f"|{_cell(', '.join(e.needs) or '-')}", ""]
    lines += ["|===", "", "=== Using a program of your own", "",
              "Only when you name it. Each entry has a variable, and `doctor` lists every one that is set:", "",
              '[cols="1,3"]', "|===", "|Variable |Stands in for", ""]
    for e in sorted(entries.values(), key=lambda e: e.name):
        lines += [f"|`{e.variable}`", f"|{_cell(e.override_hint or 'a program of your own')}", ""]
    lines += ["|===", "", "=== System libraries", "",
              f"A browser and VS Code link shared libraries, and VS Code's tests need a display server, that a fetch cannot supply. "
              f"`{name} system ensure` installs them once with `sudo`: it prints exactly what it will run and asks first, and no other "
              "command uses `sudo`. The packages are pinned for Debian and Ubuntu; on another distribution it names the libraries "
              "and stops.", "", '[cols="2,2"]', "|===", "|Library or program |Debian and Ubuntu package", ""]
    packages = {**system.APT_LIBRARIES, **system.APT_VSCODE_EXTRA}
    for lib in sorted(packages):
        lines += [f"|`{lib}`", f"|`{packages[lib]}`", ""]
    lines += ["|===", ""]
    return "\n".join(lines)


def design_systems_chapter(root: Path, reg: Registry) -> str:
    entries = design_systems.entries(root)
    lines = [header(), "[#reference-design-systems]", "== Design systems", "",
             "Each design system is a folder under `design-systems/` with its own spec and its own test harness. They are listed here as "
             f"the ontology registers them. `{reg.name} help design-systems` explains how to check or start one, and "
             f"`{reg.name} design-system show SLUG` shows one.", "",
             '[cols="3,1,1,1,3"]', "|===", "|Design system |Kind |Status |Spec |Harness", ""]
    for slug in design_systems.slugs(root):
        r = design_systems.row(root, slug, entries.get(slug))
        lines += [f"|`{slug}`", f"|{r['kind']}", f"|{r['status']}", f"|{r['spec']}", f"|{_cell(r['harness'])}", ""]
    lines += ["|===", ""]
    return "\n".join(lines)


def specs_chapter(root: Path) -> str:
    lines = [header(), "[#reference-specs]", "== The specs", "",
             "Every spec of this repository, with its status. A spec says what must be true; the enforcement register says how each "
             "requirement is enforced. The format is 0020-spec-format.", "",
             '[cols="3,1,5"]', "|===", "|Spec |Status |Subject", ""]
    for s in specs.find_specs(root):
        if s.design_system:
            continue
        lines += [f"|`{s.name}`", f"|{_cell(s.status)}", f"|{_cell(s.title)}", ""]
    lines += ["|===", ""]
    return "\n".join(lines)


def reference_files(reg: Registry, home: Path, entries: dict[str, Any]) -> dict[Path, str]:
    base = home / SRC / "chapters" / "reference"
    return {base / "commands.adoc": commands_chapter(reg), base / "checks.adoc": checks_chapter(reg),
            base / "help-topics.adoc": help_chapter(reg), base / "toolchain.adoc": toolchain_chapter(reg, entries),
            base / "design-systems.adoc": design_systems_chapter(home, reg), base / "specs.adoc": specs_chapter(home)}


# ---- the build ---------------------------------------------------------------------------------------------------

class GuideError(Exception):
    pass


def manuscript(root: Path) -> list[dict[str, str]]:
    """The chapters in manuscript order, each with the part it belongs to."""
    out: list[dict[str, str]] = []
    part = "Preface"
    for line in (root / SRC / "manuscript.adoc").read_text(encoding="utf-8").splitlines():
        m = re.match(r"^= (Part [^\n]+)$", line)
        if m:
            part = m.group(1)
            continue
        m = re.match(r"^include::(chapters/[^\[]+\.adoc)\[\]", line)
        if m:
            rel = m.group(1)
            out.append({"file": rel, "slug": Path(rel).stem, "part": part})
    slugs = [c["slug"] for c in out]
    if len(set(slugs)) != len(slugs):
        raise GuideError("two chapters share a file name, so the site would give them one page")
    return out


def _title_of(page: str, fallback: str) -> str:
    m = re.search(r"<h[12][^>]*>(.*?)</h[12]>", page, re.S)
    return re.sub(r"<[^>]+>", "", m.group(1)).strip() if m else fallback


def site_pages(root: Path, chapters_html: dict[str, str], version: str, name: str) -> dict[str, str]:
    """One page per chapter, each with the contents beside it: `{file name: html}`; the first chapter is also `index.html`."""
    chapters = manuscript(root)
    ids: dict[str, str] = {}
    titles: dict[str, str] = {}
    for ch in chapters:
        body = chapters_html[ch["slug"]]
        titles[ch["slug"]] = _title_of(body, ch["slug"].replace("-", " ").capitalize())
        for i in re.findall(r'\bid="([^"]+)"', body):
            ids.setdefault(i, ch["slug"])
        for i, t in re.findall(r'<h[2-6] id="([^"]+)">(.*?)</h[2-6]>', body, re.S):
            titles.setdefault("#" + i, re.sub(r"<[^>]+>", "", t).strip())
    pages: dict[str, str] = {}
    for n, ch in enumerate(chapters):
        slug = ch["slug"]

        def fix(m: re.Match[str]) -> str:
            target, text = m.group(1), m.group(2)
            page = ids.get(target)
            href = f"#{target}" if page in (None, slug) else f"{page}.html#{target}"
            label = titles.get("#" + target, text.strip("[]")) if text.startswith("[") and text.endswith("]") else text
            return f'<a href="{href}">{label}</a>'

        body = re.sub(r'<a href="#([^"]+)">([^<]*)</a>', fix, chapters_html[slug])
        nav: list[str] = []
        last = None
        for c in chapters:
            if c["part"] != last:
                nav.append(f'<div class="part">{html.escape(c["part"])}</div>')
                last = c["part"]
            cur = ' class="current"' if c["slug"] == slug else ""
            nav.append(f'<ul><li><a href="{c["slug"]}.html"{cur}>{html.escape(titles[c["slug"]])}</a></li></ul>')
        prev = (f'<a href="{chapters[n - 1]["slug"]}.html">&larr; {html.escape(titles[chapters[n - 1]["slug"]])}</a>' if n else "<span></span>")
        nxt = (f'<a href="{chapters[n + 1]["slug"]}.html">{html.escape(titles[chapters[n + 1]["slug"]])} &rarr;</a>'
               if n + 1 < len(chapters) else "<span></span>")
        pages[f"{slug}.html"] = (
            '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">'
            f'<title>{html.escape(titles[slug])} - {html.escape(name)} guide</title>'
            '<link rel="icon" href="../assets/favicon.png"><link rel="stylesheet" href="../assets/brand.css">'
            '<link rel="stylesheet" href="html.css"><link rel="stylesheet" href="site.css"></head>'
            '<body class="site"><nav class="site-nav" aria-label="Contents">'
            '<a class="brand" href="../index.html"><picture><source media="(prefers-color-scheme: dark)" srcset="../assets/logo-dark.webp">'
            '<img src="../assets/logo.webp" alt="Intellectual Frontiers" width="168" height="47"></picture></a>'
            f'<details open><summary>Contents</summary>{"".join(nav)}</details></nav>'
            f'<main class="site-main"><div id="content">{body}</div><div class="pager">{prev}{nxt}</div>'
            f'<footer>{html.escape(name)} guide {html.escape(version)}. The reference chapters are generated from the code.</footer></main>'
            '</body></html>')
    pages["index.html"] = pages[f"{chapters[0]['slug']}.html"]
    return pages


class _Links(HTMLParser):
    def __init__(self) -> None:
        super().__init__()
        self.hrefs: list[str] = []
        self.ids: set[str] = set()

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        a = dict(attrs)
        if a.get("id"):
            self.ids.add(a["id"] or "")
        if a.get("name") and tag == "a":
            self.ids.add(a["name"] or "")
        for key in ("href", "src", "srcset"):
            if a.get(key) and tag in ("a", "link", "img", "source"):
                self.hrefs.append((a[key] or "").split(" ")[0] if key == "srcset" else a[key] or "")


def link_findings(out: Path, pages: list[str]) -> list[str]:
    """Each relative link, image or fragment in the named pages (paths under `out`) that points at nothing."""
    parsed: dict[Path, _Links] = {}

    def read(p: Path) -> _Links | None:
        if p not in parsed:
            if not p.is_file() or p.suffix != ".html":
                return None
            lp = _Links()
            lp.feed(p.read_text(encoding="utf-8"))
            parsed[p] = lp
        return parsed[p]

    bad: list[str] = []
    for rel in pages:
        page = out / rel
        here = read(page)
        assert here is not None
        for href in here.hrefs:
            if re.match(r"^[a-z][a-z0-9+.-]*:", href, re.I) or href.startswith("//") or not href:
                continue
            path, _, frag = href.partition("#")
            target = page if not path else (page.parent / path.split("?")[0]).resolve()
            if path and not target.exists():
                bad.append(f"{rel}: {href} points at a file that does not exist")
                continue
            if frag and target.suffix == ".html":
                found = read(target)
                if found is not None and frag not in found.ids:
                    bad.append(f"{rel}: {href} points at an id the page does not have")
    return sorted(set(bad))


def copy_assets(home: Path, dest: Path) -> list[str]:
    dest.mkdir(parents=True, exist_ok=True)
    done = []
    for name, src in ASSETS.items():
        shutil.copyfile(home / src, dest / name)
        done.append(name)
    return done


def tree_for_conversion(home: Path, tmp: Path) -> Path:
    """A copy of docs-src/ with the brand's assets beside it, so that PDF and EPUB find their pictures at `assets/` and nothing in the
    clone is touched."""
    work = tmp / SRC
    shutil.copytree(home / SRC, work)
    copy_assets(home, work / "assets")
    return work


def _run(argv: list[str], env: dict[str, str], cwd: Path, timeout: int = 900) -> tuple[int, str]:
    import subprocess

    try:
        p = subprocess.run(argv, env=env, cwd=cwd, capture_output=True, timeout=timeout)
    except (OSError, subprocess.TimeoutExpired) as e:
        return 127, f"{type(e).__name__}: {e}"
    return p.returncode, (p.stdout + p.stderr).decode("utf-8", "replace")


def _css(theme: Path, name: str, assets: str) -> str:
    return (theme / name).read_text(encoding="utf-8").replace("__ASSETS__", assets)


def build_all(home: Path, out: Path, tc: Any, name: str, offline: bool, edition_notes: Callable[[str], None] | None = None) -> list[dict[str, Any]]:
    """Build the four editions into `out` (0042 FR-034). A converter that cannot be had is reported skipped with the reason; one that
    fails is reported failed with its output's tail; neither is reported built. `tc` is the invocation's toolchain."""
    import time

    from agora.core.resource import AgoraError

    say = edition_notes or (lambda line: None)
    r = tc.resolve(["jre", "asciidoctor"])
    env = r.env()
    rows: list[dict[str, Any]] = []
    out.mkdir(parents=True, exist_ok=True)
    for sub in ("guide", "assets"):
        shutil.rmtree(out / sub, ignore_errors=True)
    for f in ("guide.html", "guide.css", "guide.pdf", "guide.epub", "index.html", ".nojekyll"):
        (out / f).unlink(missing_ok=True)
    copy_assets(home, out / "assets")
    (out / ".nojekyll").write_text("", encoding="utf-8")  # the site is built; GitHub Pages must not run Jekyll over it
    theme = home / SRC / "theme"
    shutil.copyfile(home / "docs" / "index.html", out / "index.html")
    attrs = ["-a", "lang=en", "-a", "experimental", "-a", "xrefstyle=short"]

    def edition(label: str, fn: Callable[[], tuple[int, str]], produced: Path) -> None:
        say(f"building {label}")
        began = time.monotonic()
        code, text = fn()
        ok = code == 0 and produced.exists()
        rows.append({"edition": label, "status": "built" if ok else "failed", "file": str(produced.relative_to(out)),
                     "seconds": round(time.monotonic() - began, 1),
                     "reason": "" if ok else (text.strip()[-400:] or f"exit {code}")})

    with tempfile.TemporaryDirectory(prefix="agora-guide-") as t:
        work = tree_for_conversion(home, Path(t))
        manuscript_file = work / "manuscript.adoc"
        chapters = manuscript(home)

        # the multi-page site: every chapter converted in one run of the converter, then given its navigation
        def multi() -> tuple[int, str]:
            chapters_out = Path(t) / "chapters-html"
            files = [str(work / c["file"]) for c in chapters]
            code, text = _run([*r.argv("asciidoctor"), "-s", "-D", str(chapters_out), *attrs, "-a", "imagesdir=../assets", "-a", "icons!",
                               "-a", "sectnums!", *files], env, work)
            if code != 0:
                return code, text
            try:
                bodies = {c["slug"]: (chapters_out / f"{c['slug']}.html").read_text(encoding="utf-8") for c in chapters}
                pages = site_pages(home, bodies, "", name)
            except (OSError, GuideError) as e:
                return 1, str(e)
            site = out / "guide"
            site.mkdir(parents=True, exist_ok=True)
            for fname, body in pages.items():
                (site / fname).write_text(body, encoding="utf-8")
            (site / "html.css").write_text(_css(theme, "html.css", "../assets"), encoding="utf-8")
            (site / "site.css").write_text(_css(theme, "site.css", "../assets"), encoding="utf-8")
            return 0, text

        edition("multi-page HTML", multi, out / "guide" / "index.html")

        def single() -> tuple[int, str]:
            (out / "guide.css").write_text(_css(theme, "html.css", "assets"), encoding="utf-8")
            return _run([*r.argv("asciidoctor"), *attrs, "-a", "stylesheet=guide.css", "-a", "linkcss", "-a", "copycss!",
                         "-a", "imagesdir=assets", "-a", "toc=left", "-o", str(out / "guide.html"), str(manuscript_file)], env, work)

        edition("single-page HTML", single, out / "guide.html")

        try:
            pdf_r = tc.use(["jre", "asciidoctor", "asciidoctor-pdf"])
        except AgoraError as e:
            rows.append({"edition": "PDF", "status": "skipped", "file": "guide.pdf", "seconds": 0.0, "reason": e.message})
        else:
            themes = Path(t) / "pdf-theme"
            themes.mkdir()
            shutil.copyfile(theme / "pdf-theme.yml", themes / "if-press-theme.yml")
            shutil.copyfile(home / ASSETS["logo.png"], themes / "logo.png")
            edition("PDF", lambda: _run([*pdf_r.argv("asciidoctor-pdf"), "-b", "pdf", *attrs, "-a", f"pdf-themesdir={themes}",
                                         "-a", "pdf-theme=if-press", "-a", "imagesdir=assets", "-o", str(out / "guide.pdf"),
                                         str(manuscript_file)], pdf_r.env(), work), out / "guide.pdf")

        edition("EPUB", lambda: _run([*r.argv("asciidoctor"), "-b", "epub3", *attrs, "-a", f"epub3-stylesheet={theme / 'epub.css'}",
                                       "-a", "imagesdir=assets", "-o", str(out / "guide.epub"), str(manuscript_file)], env, work),
                out / "guide.epub")
    return rows


def site_links(out: Path) -> list[str]:
    pages = sorted(str(p.relative_to(out)) for p in (out / "guide").glob("*.html")) if (out / "guide").is_dir() else []
    if (out / "index.html").is_file():
        pages.append("index.html")
    return link_findings(out, pages)
