"""The agent skill, `.claude/skills/agora/SKILL.md`, written from the registry alone (0041-command-line FR-037; 0042-agora FR-028).

Nothing here reads a spec, a design or any other file of the repository: the file changes only when the registry does, so
`fresh` proves it current. Every list is sorted, so the output is deterministic.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

from agora.core.describe import command_data
from agora.core.registry import CATEGORIES, WRITES, Registry
from agora.core.types import ArgType, Choice, Dynamic, Pattern

PATH = Path(".claude") / "skills" / "agora" / "SKILL.md"
GENERATOR = "agent-skill"
REWRITE = "skill generate"

CATEGORY_HELP = {
    "read": "changes nothing",
    "check": "verifies, and changes nothing tracked",
    "record": "appends a fact to the tracked record",
    "build": "writes derived output that is not itself the record",
    "generate": "rewrites tracked generated files",
    "decision": "changes what only a person decides: for a person, in the terminal or the editor; never over MCP",
    "setup": "changes the clone's own environment (a lock, a fetched toolchain entry, a running server)",
}


def _cell(text: Any) -> str:
    return str(text).replace("|", "\\|").replace("\n", " ")


def _type_row(reg: Registry, t: ArgType) -> tuple[str, str, str]:
    if isinstance(t, Choice):
        eg = ", ".join(t.choices(None))
    elif isinstance(t, Pattern) or (type(t).examples is not ArgType.examples and not isinstance(t, Dynamic)) \
            or (isinstance(t, Dynamic) and type(t).examples is not Dynamic.examples):
        eg = ", ".join(t.examples(None))
    else:
        eg = "a value `<noun> list` or `--complete` offers"
    return t.name, t.doc, eg


def text(reg: Registry) -> str:
    name = reg.name
    commands = sorted(reg.commands.values(), key=lambda c: c.id)
    nouns = sorted(reg.nouns)
    decisions = [c.id for c in commands if c.category == "decision"]
    over_mcp = [c for c in commands if "mcp" in reg.surfaces_of(c) and c.category != "decision"]
    out: list[str] = []
    w = out.append
    w("---")
    w(f"name: {name}")
    w(f"description: Use {name}, this repository's command line, to read its specs, requirements, design systems and brands, to run its checks, "
      "builds and generators, and to propose a change for a person to decide. Run it as ./agora from the repository root.")
    w("---")
    w(f"<!-- Generated by the {GENERATOR} generator from {name}'s registry (tools/{name}/). Do not edit it by hand: run "
      f"`{name} {REWRITE}` to rewrite it, `{name} fresh` to prove it current. -->")
    w("")
    w(f"# {name}")
    w("")
    w(f"`{name}` is this repository's one command line. Its audience is `{reg.audience}`. It calls no AI model, never commits or pushes, and "
      "keeps no record but Git: a command that records or generates writes tracked files and leaves the commit to a person.")
    w("")
    w("## How to call it")
    w("")
    w(f"- `{name} <noun> <verb> [ID] [--options]`; the ID is the first word after the verb. Verbs: {', '.join(f'`{v}`' for v in _verbs())}.")
    w(f"- Repository-wide commands take no noun: {', '.join(f'`{c.id}`' for c in commands if len(c.words) == 1)}.")
    w("- `--json` on any command gives one JSON document `{schema, audience, kind, id, data, links, actions}`; `links` and `actions` say what "
      "to run next. A failure is a resource of kind `error` with a stable `code` and the actions to take next.")
    w("- Exit status: 0 success; 1 it ran and what it checked failed; 2 usage or an invalid argument; 3 a missing package, program or "
      "offline prerequisite.")
    w("- `--dry-run` on any command that writes shows what it would change and writes nothing. Run it first.")
    w(f"- `{name} context RESOURCE` (for example `{name} context spec:0020`) returns what you need to work on one resource: the resource, the "
      "specs and requirements that govern it, its links, its actions and its files, bounded, saying what it left out.")
    w(f"- `{name} command list` and `{name} command show COMMAND` read the registry itself; `{name} --help` shows the shape.")
    w("")
    w("## What you may do, by category")
    w("")
    w("| Category | Means |")
    w("| --- | --- |")
    for c in CATEGORIES:
        w(f"| `{c}` | {CATEGORY_HELP[c]} |")
    w("")
    w(f"A `decision` command is for a person: {', '.join(f'`{d}`' for d in decisions)}. Do not run one for a person. To ask for a decision, "
      f"draft it with `{name} proposal new RESOURCE --reason TEXT --run COMMAND --field NAME=VALUE`; a person reviews it and runs "
      f"`{name} proposal advance ID`. A proposal is a tracked file under `.agora/proposals/`.")
    w("")
    w("## Nouns")
    w("")
    w("| Noun | Is |")
    w("| --- | --- |")
    for n in nouns:
        w(f"| `{n}` | {_cell(reg.nouns[n])} |")
    w("")
    w("## Commands")
    w("")
    w("Surfaces: `terminal` always; `editor` a person's editor; `mcp` the MCP server. Each row's example is its usage line.")
    w("")
    w("| Command | Category | Surfaces | Does | Example |")
    w("| --- | --- | --- | --- | --- |")
    for c in commands:
        d = command_data(reg, c)
        w(f"| `{c.id}` | `{c.category}` | {', '.join(d['surfaces'])} | {_cell(c.help)} | `{_cell(d['usage'])}` |")
    w("")
    w("### Arguments and options")
    w("")
    for c in commands:
        d = command_data(reg, c)
        parts = [f"`{a['name']}` ({a['type']}{', zero or more' if a['many'] else '' if a['required'] else ', optional'}): {_cell(a['help'])}"
                 for a in d["arguments"]]
        parts += [f"`{o['flag']}` ({o['type']}{', required' if o['required'] else ''}): {_cell(o['help'])}" for o in d["options"]]
        if parts:
            w(f"- `{c.id}`")
            out.extend(f"  - {p}" for p in parts)
    w("")
    w("## Typed arguments")
    w("")
    w("A value that fails its type is an error resource that names the type and gives examples.")
    w("")
    w("| Type | Is | Examples |")
    w("| --- | --- | --- |")
    for t in sorted(reg.types.values(), key=lambda t: t.name):
        n, doc, eg = _type_row(reg, t)
        w(f"| `{n}` | {_cell(doc)} | {_cell(eg)} |")
    w("")
    w("## Checks")
    w("")
    w(f"Every check runs through `{name} check [SECTION...] [--scope ID] [--suite SUITE] [--changed]`; `--changed` runs only the sections "
      f"whose watched paths Git reports changed. With nothing named it runs every section. `{name} fresh [GENERATOR...]` proves generated files "
      f"current and writes nothing; `{name} test` runs agora's own tests; `{name} doctor` reports what is present and what is missing.")
    w("")
    suites = {s: v["sections"] for s, v in sorted(reg.suites.items())}
    w("| Section | Checks | Scope | Suites |")
    w("| --- | --- | --- | --- |")
    for s in sorted(reg.sections.values(), key=lambda s: s.name):
        in_suites = ", ".join(f"`{k}`" for k, v in suites.items() if s.name in v) or "none"
        w(f"| `{s.name}` | {_cell(s.help)} | {s.scope or 'none'} | {in_suites} |")
    w("")
    w("## Generators")
    w("")
    w("A generated file carries a header naming its generator and must not be edited by hand; rewrite it with the command shown.")
    w("")
    w("| Generator | Writes | Rewritten by |")
    w("| --- | --- | --- |")
    for g in sorted(reg.generators.values(), key=lambda g: g.name):
        w(f"| `{g.name}` | {_cell(g.help)} | `{name} {g.command}` |")
    w("")
    w("## MCP")
    w("")
    w(f"`{name} mcp serve` speaks MCP over standard input and output. It lists these {len(over_mcp)} commands as tools, named with spaces made "
      "underscores (`spec_show`, `check`), each taking the arguments above by name; a tool that writes takes `dry_run`, which is true unless "
      "you pass false. A `decision` command is never a tool and a call to one is refused with the error resource `decision-refused`, "
      "whose next action is `proposal new`. Resources are readable by URI: "
      + ", ".join(f"`{name}://{u}`" for u in ("spec/ID", "requirement/SPEC/FR-NNN", "design-system/SLUG", "brand/SLUG", "ontology/ID",
                                              "command/WORDS", "proposal/ID", "context/KIND:ID")) + ".")
    w("")
    w("| Tool | Writes |")
    w("| --- | --- |")
    for c in over_mcp:
        w(f"| `{c.id.replace(' ', '_')}` | {'yes, dry run by default' if c.category in WRITES else 'no'} |")
    w("")
    return "\n".join(out)


def _verbs() -> tuple[str, ...]:
    from agora.core.registry import VERBS
    return VERBS
