name = "jre"
version = "21.0.12.1+1"
summary = "a Temurin Java runtime"
kind = "archive"
strip = 1
bin = "bin"
env = { JAVA_HOME = "{dir}" }
provides = { java = "bin/java" }

[platforms.linux-x64]
url = "https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.12.1%2B1/OpenJDK21U-jre_x64_linux_hotspot_21.0.12.1_1.tar.gz"
sha256 = "2413149700df0f7d440500a84a8f764c535f21e5a5e87d38328b64eec2c5b500"

[platforms.linux-arm64]
url = "https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.12.1%2B1/OpenJDK21U-jre_aarch64_linux_hotspot_21.0.12.1_1.tar.gz"
sha256 = "14be1f35ebdbd1f6e8d57eb911a3ffb74d6d9aa255abc5daf2b1302002cf2cf2"
